from header_common import *
from header_items import *
from header_troops import *
from header_skills import *

####################################################################################################################
#  Each troop contains the following fields:
#  1) Troop id (string): used for referencing troops in other files. The prefix trp_ is automatically added before each troop-id
#  2) Toop name (string)
#  3) Plural troop name (string)
#  4) Troop flags (int). See header_troops.py for a list of available flags
#  5) Scene and entry
#   5.1) Scene (only applicable to heroes)
#   5.2) Entry point using the entry() function: for example, entry(15)
#  6) Reserved (int). Put constant "reserved" or 0
#  7) Faction (int)
#  8) Inventory (list): Must be a list of items
#  9) Attributes (int): Example usage:
#           str_6|agi_6|int_4|cha_5|level(5)
# 10) Weapon proficiencies (int): Example usage:
#           wp_one_handed(55)|wp_two_handed(90)|wp_polearm(36)|wp_archery(80)|wp_crossbow(24)|wp_throwing(45)
# 11) Skills (int): See header_skills.py to see a list of skills. Example:
#           knows_ironflesh_3|knows_power_strike_2|knows_athletics_2|knows_riding_2
# 12) Face code (int): You can obtain the face code by pressing ctrl+E in face generator screen
# 13) Face code (int)(2) (only applicable to regular troops, can be omitted for heroes):
#     The game will create random faces between Face code 1 and face code 2 for generated troops
# 14) Troop image (string): If this variable is set, the troop will use an image rather than its 3D visual during the conversations
####################################################################################################################

def wp(x):
  return wp_one_handed(x)|wp_two_handed(x)|wp_polearm(x)|wp_archery(x)|wp_crossbow(x)|wp_throwing(x)

def wpe(m,a,c,t):
  return wp_one_handed(m)|wp_two_handed(m)|wp_polearm(m)|wp_archery(a)|wp_crossbow(c)|wp_throwing(t)

def wpex(o,w,p,a,c,t):
  return wp_one_handed(o)|wp_two_handed(w)|wp_polearm(p)|wp_archery(a)|wp_crossbow(c)|wp_throwing(t)

def wp_melee(x):
  return wp_one_handed(x + 20)|wp_two_handed(x)|wp_polearm(x + 10)

reserved = 0
no_scene = 0

default_face_1 = 0x0000000400000001124000000020000000000000001c00800000000000000000
default_face_2 = 0x0000000cbf00230c4deeffffffffffff00000000001efff90000000000000000

tf_guarantee_all = tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves|tf_guarantee_helmet|tf_guarantee_horse|tf_guarantee_shield|tf_guarantee_ranged
tf_guarantee_all_wo_ranged = tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves|tf_guarantee_helmet|tf_guarantee_horse|tf_guarantee_shield

# troops have 30 charisma and 10 weapon master to stop the game engine from adding random skill levels
pw_attr = cha_30|level(1)
knows_pw = knows_weapon_master_10

troops = [
  ["player","Player","Player",tf_hero|tf_unmoveable_in_party_window,no_scene,reserved,0, [],
   str_15|agi_15|int_4|cha_4,wp(15),0,0x000000018000000136db6db6db6db6db00000000001db6db0000000000000000],
  ["multiplayer_profile_troop_male","multiplayer_profile_troop_male","multiplayer_profile_troop_male", tf_hero|tf_guarantee_all,0,0,0, [],
   str_14, 0, 0, 0x000000018000000136db6db6db6db6db00000000001db6db0000000000000000],
  ["multiplayer_profile_troop_female","multiplayer_profile_troop_female","multiplayer_profile_troop_female", tf_hero|tf_female|tf_guarantee_all,0,0,0, [],
   str_14, 0, 0, 0x000000018000000136db6db6db6db6db00000000001db6db0000000000000000],
  ["temp_troop","Temp Troop","Temp Troop",tf_hero,no_scene,reserved,0,[],0,0,0,0],
  #["temp_troop","Temp Troop","Temp Troop",tf_guarantee_all,0,0,"fac_commoners",
  # ["itm_strange_armor","itm_strange_boots","itm_strange_helmet","itm_strange_sword","itm_strange_great_sword","itm_strange_short_sword","itm_long_bow","itm_barbed_arrows","itm_tab_shield_pavise_c"],
  # str_15|agi_15|pw_attr,wpex(600,600,600,600,600,600),knows_pw|knows_ironflesh_10|knows_power_strike_3|knows_shield_10|knows_power_draw_5|knows_athletics_2,default_face_1,default_face_2],  
####################################################################################################################
# Troops before this point are hardwired into the game and their order should not be changed!
####################################################################################################################

  #GGG:change name
  ["peasant","Peasant","a peasant",tf_guarantee_all,0,0,"fac_commoners", #GGG:civilian
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  #["serf","Serf","a serf",tf_guarantee_all,0,0,"fac_commoners",
  # ["itm_ragged_shirt","itm_hatchet","itm_blunt_sickle","itm_old_knife"],
  # str_5|agi_5|pw_attr,wpex(30,30,30,0,0,50),knows_pw|knows_power_strike_1|knows_labouring_5|knows_engineer_1|knows_tailoring_1|knows_herding_3|knows_riding_1,default_face_1,default_face_2],
  ["serf","Peasant","a peasant",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_ragged_shirt","itm_hatchet","itm_blunt_sickle","itm_old_knife"],
   str_8|agi_8|pw_attr,wpex(70,40,70,10,40,50),knows_pw|knows_ironflesh_2|knows_power_strike_1|knows_riding_1|knows_labouring_5|knows_engineer_1|knows_tailoring_1|knows_herding_3,default_face_1,default_face_2],
  ["militia","Militia","a militia",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_ragged_woolen_cap","itm_old_coarse_tunic","itm_blunt_falchion"],
   str_10|agi_9|pw_attr,wpex(70,40,70,10,40,50),knows_pw|knows_ironflesh_2|knows_power_strike_2|knows_athletics_2|knows_riding_1|knows_labouring_1|knows_herding_2,default_face_1,default_face_2],
  #["huntsman","Huntsman","a huntsman",tf_guarantee_all,0,0,"fac_commoners",
  # ["itm_ragged_woolen_cap","itm_old_coarse_tunic","itm_crude_bow","itm_bent_arrows"],
  # str_9|agi_9|pw_attr,wpex(60,35,50,100,100,50),knows_pw|knows_ironflesh_1|knows_power_strike_1|knows_power_draw_2|knows_athletics_1|knows_riding_1|knows_labouring_1|knows_herding_3,default_face_1,default_face_2],
  ["huntsman","Huntsman","a huntsman",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_ragged_woolen_cap","itm_old_coarse_tunic","itm_crude_bow","itm_bent_arrows"],
   str_9|agi_9|pw_attr,wpex(75,45,75,100,100,50),knows_pw|knows_ironflesh_1|knows_power_strike_1|knows_power_draw_2|knows_athletics_3|knows_riding_1|knows_labouring_1|knows_herding_3,default_face_1,default_face_2],

  ["craftsman","Craftsman","a craftsman",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_old_coarse_tunic"],
   str_8|agi_8|pw_attr,wpex(50,30,30,20,20,20),knows_pw|knows_power_strike_1|knows_riding_1|knows_engineer_2|knows_labouring_1|knows_tailoring_3,default_face_1,default_face_2],
  ["healer","Healer","a healer",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_linen_tunic"],
   str_8|agi_8|pw_attr,wpex(40,10,20,0,0,5),knows_pw|knows_riding_1|knows_wound_treatment_1|knows_labouring_1|knows_tailoring_2|knows_herding_1,default_face_1,default_face_2],
  ["footman","Footman","a footman",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_ragged_woolen_cap","itm_old_coarse_tunic","itm_old_tabard","itm_tattered_wrapping_boots","itm_crude_spear","itm_rusty_sword","itm_chipped_falchion"],
   str_15|agi_14|pw_attr,wpex(100,100,130,10,45,80),knows_pw|knows_ironflesh_5|knows_power_strike_4|knows_power_throw_2|knows_shield_1|knows_athletics_5|knows_riding_2|knows_sailing_3,default_face_1,default_face_2],
  ["archer","Archer","an archer",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_tattered_headcloth","itm_old_coarse_tunic","itm_old_tabard","itm_tattered_wrapping_boots","itm_crude_bow","itm_bent_arrows","itm_blunt_falchion"],
   str_14|agi_14|pw_attr,wpex(90,60,70,150,50,50),knows_pw|knows_ironflesh_4|knows_power_strike_2|knows_power_draw_4|knows_athletics_4|knows_riding_2|knows_sailing_3,default_face_1,default_face_2],
  ["crossbowman","Crossbowman","a crossbowman",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_ragged_woolen_cap","itm_old_coarse_tunic","itm_old_tabard","itm_tattered_wrapping_boots","itm_flimsy_crossbow","itm_crude_bolts","itm_blunt_falchion"],
   str_14|agi_14|pw_attr,wpex(90,60,60,50,150,50),knows_pw|knows_ironflesh_3|knows_power_strike_3|knows_athletics_4|knows_riding_2|knows_sailing_3,default_face_1,default_face_2],
  ["lancer","Lancer","a lancer",tf_mounted|tf_guarantee_all,0,0,"fac_commoners",
   ["itm_ragged_woolen_cap","itm_tattered_headcloth","itm_old_coarse_tunic","itm_old_tabard","itm_tattered_wrapping_boots","itm_bent_lance"],
   str_14|agi_14|pw_attr,wpex(90,60,120,10,30,80),knows_pw|knows_ironflesh_3|knows_power_strike_3|knows_power_throw_2|knows_athletics_1|knows_riding_6,default_face_1,default_face_2], #+knows_power_throw_2
  ["man_at_arms","Man at Arms","a man at arms",tf_mounted|tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_old_tabard","itm_old_hide_boots","itm_rusty_sword","itm_worn_sword","itm_old_shield"],
   str_15|agi_15|pw_attr,wpex(105,120,110,20,50,30),knows_pw|knows_ironflesh_4|knows_power_strike_4|knows_shield_1|knows_athletics_2|knows_riding_4,default_face_1,default_face_2],
  ["sergeant","Sergeant","a sergeant",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_old_tabard","itm_old_hide_boots","itm_rusty_sword","itm_worn_sword","itm_old_shield"],
   str_15|agi_15|pw_attr,wpex(110,125,110,20,60,40),knows_pw|knows_ironflesh_5|knows_power_strike_4|knows_shield_2|knows_athletics_5|knows_riding_2|knows_power_throw_2,default_face_1,default_face_2], #+knows_power_throw_2
  ["engineer","Engineer","an engineer",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_tattered_headcloth","itm_old_coarse_tunic","itm_ragged_leather_apron","itm_old_hide_boots","itm_tattered_wrapping_boots","itm_old_knife"],
   str_13|agi_12|pw_attr,wpex(95,50,60,30,65,50),knows_pw|knows_ironflesh_2|knows_power_strike_2|knows_athletics_2|knows_engineer_5|knows_riding_2|knows_looting_1|knows_sailing_4,default_face_1,default_face_2], #10->13 90->95
  ["master_smith","Master Smith","a master smith",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_old_tabard","itm_ragged_leather_apron","itm_old_hide_boots","itm_rusty_sword","itm_worn_sword"],
   str_12|agi_12|pw_attr,wpex(100,55,70,30,70,50),knows_pw|knows_ironflesh_3|knows_power_strike_3|knows_athletics_2|knows_engineer_7|knows_riding_2|knows_looting_2|knows_sailing_4,default_face_1,default_face_2],
  ["doctor","Doctor","a doctor",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_linen_tunic","itm_ripped_woolen_hose"],
   str_10|agi_10|pw_attr,wpex(70,40,50,10,20,30),knows_pw|knows_athletics_2|knows_power_strike_2|knows_wound_treatment_5|knows_riding_2,default_face_1,default_face_2], 
  ["sailor","Sailor","a sailor",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_stained_felt_hat_b","itm_ragged_woolen_cap","itm_old_coarse_tunic","itm_old_tabard","itm_club","itm_chipped_falchion"],
   str_14|agi_12|pw_attr,wpex(95,70,80,30,40,70),knows_pw|knows_ironflesh_3|knows_power_strike_3|knows_power_throw_5|knows_athletics_2|knows_sailing_9|knows_riding_1,default_face_1,default_face_2],#+knows_power_throw_5
  ["traveler","Traveler","a traveler",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_old_hide_boots","itm_tattered_wrapping_boots","itm_old_knife"],
   str_10|agi_13|pw_attr,wpex(60,40,50,10,20,60),knows_pw|knows_ironflesh_1|knows_power_strike_2|knows_athletics_5|knows_sailing_7|knows_riding_3|knows_labouring_1|knows_herding_1|knows_tailoring_2,default_face_1,default_face_2],
  ["herdsman","Herdsman","a herdsman",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_tattered_wrapping_boots","itm_old_knife"],
   str_10|agi_14|pw_attr,wpex(50,35,40,0,10,40),knows_pw|knows_power_strike_1|knows_athletics_5|knows_labouring_2|knows_herding_5,default_face_1,default_face_2],
  ["lord","Lord","the lord",tf_mounted|tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_tabard","itm_ripped_woolen_hose","itm_old_hide_boots","itm_worn_sword"],
   str_15|agi_15|pw_attr,wpex(115,115,115,50,70,50),knows_pw|knows_leadership_1|knows_ironflesh_6|knows_power_strike_4|knows_shield_2|knows_athletics_2|knows_riding_5,default_face_1,default_face_2], 
  ["ruffian","Ruffian","a ruffian",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_club","itm_spiked_club"],
   str_14|agi_12|pw_attr,wpex(80,65,80,10,20,80),knows_pw|knows_ironflesh_3|knows_power_strike_4|knows_athletics_3|knows_riding_1|knows_looting_2,default_face_1,default_face_2],
  ["brigand","Brigand","a brigand",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_knife","itm_blunt_falchion"],
   str_12|agi_12|pw_attr,wpex(70,40,70,100,60,70),knows_pw|knows_ironflesh_2|knows_power_strike_2|knows_power_draw_3|knows_athletics_3|knows_riding_1|knows_looting_6|knows_sailing_4,default_face_1,default_face_2], 
  ["mercenary","Mercenary","a mercenary",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_ragged_woolen_cap","itm_stained_felt_hat_b","itm_tattered_headcloth","itm_old_coarse_tunic","itm_old_tabard","itm_tattered_wrapping_boots","itm_old_hide_boots","itm_chipped_falchion","itm_rusty_sword","itm_crude_spear","itm_old_shield","itm_flimsy_crossbow","itm_crude_bolts"],
   str_14|agi_14|pw_attr,wpex(90,70,80,30,75,70),knows_pw|knows_ironflesh_3|knows_power_strike_3|knows_athletics_3|knows_riding_2|knows_engineer_1|knows_sailing_3|knows_tailoring_1,default_face_1,default_face_2],
  #GGG:outlaw rating
  ["prisoner","prisoner","a prisoner",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_ragged_woolen_cap","itm_old_coarse_tunic","itm_blunt_falchion"],
   str_5|agi_5|pw_attr,wpex(30,30,30,0,0,50),knows_pw|knows_power_strike_1|knows_labouring_5|knows_engineer_1|knows_tailoring_1|knows_herding_3,default_face_1,default_face_2],

  #GGG:skill menu
  ["hero_1","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_2","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_3","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_4","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_5","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_6","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_7","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_8","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_9","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_10","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_11","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_12","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_13","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_14","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_15","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_16","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_17","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_18","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_19","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_20","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_21","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_22","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_23","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_24","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_25","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_26","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_27","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_28","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_29","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_30","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_31","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_32","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_33","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_34","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_35","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_36","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_37","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_38","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_39","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_40","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_41","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_42","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_43","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_44","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_45","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_46","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_47","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_48","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_49","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_50","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_51","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_52","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_53","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_54","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_55","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_56","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_57","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_58","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_59","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_60","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_61","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_62","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_63","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_64","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_65","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_66","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_67","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_68","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_69","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_70","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_71","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_72","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_73","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_74","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_75","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_76","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_77","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_78","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_79","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_80","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_81","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_82","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_83","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_84","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_85","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_86","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_87","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_88","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_89","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_90","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_91","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_92","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_93","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_94","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_95","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_96","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_97","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_98","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_99","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_100","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_101","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_102","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_103","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_104","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_105","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_106","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_107","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_108","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_109","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_110","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_111","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_112","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_113","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_114","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_115","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_116","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_117","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_118","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_119","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_120","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_121","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_122","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_123","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_124","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_125","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_126","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_127","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_128","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_129","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_130","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_131","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_132","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_133","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_134","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_135","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_136","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_137","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_138","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_139","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_140","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_141","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_142","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_143","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_144","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_145","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_146","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_147","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_148","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_149","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_150","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_151","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_152","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_153","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_154","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_155","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_156","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_157","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_158","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_159","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_160","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_161","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_162","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_163","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_164","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_165","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_166","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_167","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_168","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_169","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_170","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_171","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_172","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_173","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_174","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_175","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_176","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_177","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_178","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_179","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_180","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_181","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_182","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_183","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_184","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_185","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_186","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_187","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_188","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_189","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_190","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_191","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_192","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_193","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_194","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_195","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_196","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_197","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_198","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_199","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  ["hero_200","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(40,20,20,0,0,20),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],

  ["hero_end","Hero","a hero",tf_guarantee_all,0,0,"fac_commoners", 
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"],
   str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw|knows_power_strike_1|knows_labouring_2|knows_tailoring_1|knows_riding_1,default_face_1,default_face_2],
  #
  ["godlike_hero","Godlike Hero","a godlike hero",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_red_shirt","itm_linen_tunic","itm_woolen_hose","itm_invisible_sword","itm_wand_of_law","itm_admin_scalpel"],
   str_30|agi_30|pw_attr,wpex(300,300,300,300,300,300),knows_pw|knows_ironflesh_10|knows_power_strike_10|knows_power_draw_10|knows_power_throw_10|knows_shield_10|knows_athletics_10|knows_riding_10|knows_engineer_10|knows_wound_treatment_10|knows_looting_10|knows_labouring_10|knows_sailing_10|knows_tailoring_10|knows_herding_10,default_face_1,default_face_2],
  ["playable_troops_end","playable_troops_end","playable_troops_end",0,0,0,0,[],0,0,0,0,0],

  #GGG:bots
  ["royal_footman","Royal Footman","a royal footman",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_footman_helmet","itm_mail_with_surcoat","itm_mail_chausses","itm_mail_mittens","itm_military_cleaver_b","itm_tab_shield_pavise_c","itm_war_spear","itm_glaive","itm_throwing_axes"],
   str_15|agi_14|pw_attr,wpex(300,10,300,10,10,200),knows_pw|knows_ironflesh_5|knows_power_strike_4|knows_power_throw_2|knows_shield_5|knows_athletics_5|knows_power_throw_2,default_face_1,default_face_2],
  ["royal_man_at_arms","Royal Man at Arms","a royal man at arms",tf_mounted|tf_guarantee_all,0,0,"fac_commoners",
   ["itm_full_helm","itm_coat_of_plates","itm_iron_greaves","itm_mail_mittens","itm_tab_shield_kite_cav_b","itm_sword_medieval_d_long","itm_throwing_spears"],
   str_15|agi_15|pw_attr,wpex(300,10,20,20,50,200),knows_pw|knows_ironflesh_5|knows_power_strike_4|knows_shield_6|knows_athletics_2|knows_power_throw_1,default_face_1,default_face_2],
  ["royal_archer","Royal Archer","a royal archer",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_footman_helmet","itm_mail_with_surcoat","itm_mail_chausses","itm_mail_mittens","itm_military_cleaver_b","itm_long_bow","itm_barbed_arrows","itm_barbed_arrows"],
   str_15|agi_15|pw_attr,wpex(300,300,10,200,10,10),knows_pw|knows_ironflesh_5|knows_power_strike_3|knows_power_draw_5|knows_athletics_2,default_face_1,default_face_2],
  ["royal_lord","Royal Lord","the royal lord",tf_mounted|tf_guarantee_all,0,0,"fac_commoners",
   ["itm_winged_great_helmet","itm_plate_armor","itm_plate_boots","itm_gauntlets","itm_steel_shield","itm_bastard_sword_b"],
   str_15|agi_15|pw_attr,wpex(600,600,600,50,70,50),knows_pw|knows_leadership_1|knows_ironflesh_10|knows_power_strike_4|knows_shield_10|knows_athletics_2|knows_riding_5,default_face_1,default_face_2],
  #

  ["inactive_players_array","inactive_players_array","inactive_players_array",0,0,0,0,[],0,0,0,0,0],
  ["mission_data","mission_data","mission_data",0,0,0,0,[],0,0,0,0,0],
  ["banner_background_color_array","banner_background_color_array","banner_background_color_array",0,0,0,0,[],0,0,0,0,0],
  ["temp_array","temp_array","temp_array",0,0,0,0,[],0,0,0,0,0],
  ["last_chat_message","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_0","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_1","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_2","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_3","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_4","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_5","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_6","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_7","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_8","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_9","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_10","-","-",0,0,0,0,[],0,0,0,0,0],
  ["chat_overlay_ring_buffer_end","-","-",0,0,0,0,[],0,0,0,0,0],
  ["ship_array","ship_array","ship_array",0,0,0,0,[],0,0,0,0,0],
  ["cart_array","cart_array","cart_array",0,0,0,0,[],0,0,0,0,0],
  ["removed_scene_props","removed_scene_props","removed_scene_props",0,0,0,0,[],0,0,0,0,0],
  ["animation_menu_strings","animation_menu_strings","animation_menu_strings",0,0,0,0,[],0,0,0,0,0],
  ["animation_durations","animation_durations","animation_durations",0,0,0,0,[],0,0,0,0,0],

  ["npc1","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
  ["npc2","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
  ["npc3","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
  ["npc4","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
  ["npc5","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
  ["npc6","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
  ["npc7","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
  ["npc8","unknow","unknow",tf_guarantee_all,0,0,"fac_commoners",
   ["itm_old_coarse_tunic","itm_ragged_shirt","itm_old_knife","itm_hatchet"], str_8|agi_8|pw_attr,wpex(50,30,30,0,0,30),knows_pw,default_face_1,default_face_2],
]
